apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
    - kubeflow
    - knative-serving
    - auth
    - kserve
    - knative-eventing