apiVersion: admissionregistration.k8s.io/v11
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: $(podDefaultsNamespace)/$(podDefaultsCertName)
  