apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- serverless-operator.yaml
- knative-serving.yaml
- knative-eventing.yaml
- knative-serving-crd.yaml
- knative-eventing-crd.yaml
#- gateway-selectors.yaml

