apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Kubeflow Pipelines
- ../../apps/pipeline/upstream/env/platform-agnostic-multi-user
# KFServing
- ../../apps/kfserving/upstream/overlays/kubeflow
# Katib
- ../../apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../../apps/centraldashboard/upstream/overlays/kserve
# Admission Webhook
- ../../apps/admission-webhook/upstream/overlays/cert-manager
# Notebook Controller
- ../../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Jupyter Web App
- ../../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../../apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../../apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
- ../../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
- ../../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- ../../apps/training-operator/upstream/overlays/kubeflow
# User namespace
- ../../common/user-namespace/base

# KServe
- ../../contrib/kserve/kserve
- ../../contrib/kserve/models-web-app/overlays/kubeflow
- ../../common/istio-openshift/istio-install/base