apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  installation_tag: My Kiali
  istio_namespace: istio-system
  deployment:
    logger:
      log_level: debug
    namespace: istio-system
    view_only_mode: false