apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- knative-eventing-crd.yaml
- knative-serving-crd.yaml
- eventing-post-install-jobs.yaml
- istio-authorization-policy.yaml
- cluster-role-patch-eventing.yaml
- cluster-role-patch-serving.yaml
- net-istio.yaml
- config-deployment.yaml

patches:
- patches/gateway.yaml
- patches/clusterrole-patch.yaml
- patches/configmap-patch.yaml
- patches/service-labels.yaml
#- patches/sidecar-injection.yaml