apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# KNative
- ../../common/knative-openshift/base
#- ../common/knative/knative-serving/base
#- ../common/knative/knative-serving/overlays/gateways
#- ../common/knative/knative-eventing/base
- ../../common/istio-openshift/cluster-local-gateway/base
# Kubeflow namespace
- ../../common/kubeflow-namespace/base
# Kubeflow Roles
- ../../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../../common/istio-openshift/kubeflow-istio-resources/base
# KServe
#- ../../contrib/kserve/kserve
#- ../../contrib/kserve/models-web-app/overlays/kubeflow
