---
apiVersion: v1
kind: Namespace
metadata:
  name: sso
  labels:
    kubernetes.io/metadata.name: sso
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: 'Single Sign On'

---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: 'Service Mesh'

---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    control-plane: kubeflow
    istio-injection: enabled
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: 'Kubeflow'

---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    istio-injection: enabled
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: Authentication

---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    istio-injection: enabled
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: 'Knative Serving'
 
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    istio-injection: enabled
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: 'Knative Eventing'

---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
  labels:
    istio-injection: enabled
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: 'Kubeflow KServe'

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat 
  annotations:
    openshift.io/node-selector: ""
    openshift.io/display-name: 'Elastic Search'
  labels:
    openshift.io/cluster-monitoring: "true"
    project: openshift-operators-redhat

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    openshift.io/node-selector: ""
    openshift.io/display-name: 'Cluster Logging'
  labels:
    openshift.io/cluster-monitoring: "true"
    
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    openshift.io/node-selector: ""
    openshift.io/display-name: 'Certificate Authority'
  
    