apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

# SSO Operator
- ../../common/openshift-sso/namespace
- ../../common/openshift-sso/base
# OIDC Authservice
- ../../common/oidc-authservice/base
# Dex
- ../../common/dex/overlays/istio
