apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

# SSO Realm
- sso-realm.yaml
# OIDC Authservice
- ../../common/oidc-authservice/base
# Dex
- ../../common/dex/overlays/istio
